from django.core.exceptions import ValidationError
#from .models import User


#def validate_uniq_emai(value):
#    if User.objects.filter(email=value).exists():
#        raise ValidationError('email уже занят')
